### ISSUE TITLE
Why do we need a version.txt file

### ISSUE THREAD

**Issue by Vad1mo** [netzwerg/gradle-release-plugin#14]
First of thanks for the plugin. I like the plugins outstanding simplicity.

I have a question regarding the version.txt file. Why is it needed? Would it not be better to just update the gradle build file instead?

**Comment by netzwerg** [comment]
Thank you for your positive feedback!

You are correct, keeping the version number directly in the build file would be even simpler. However, it is quite a common practice to include a `version.txt` file in your final release bundle, e.g. when creating a distributable ZIP. That's why the plugin also exposes the `release.versionFile` property to reference the file, e.g. like

```groovy
apply plugin: 'java-library-distribution'

distributions {
    main {
        contents {
            from release.versionFile
            // ...
        }
    }
}
```
