### ISSUE TITLE
push=true is not pushing

### ISSUE THREAD

**Issue by Vad1mo** [netzwerg/gradle-release-plugin#15]
I am calling  `gradle -x test -s -d release -Prelease.push=true` from my Jenkins/CI server to create tag and push the changes into git.

From the debug output I see that a tag was committed successfully but it is never pushed to origin/remote.  

```
14:37:51.655 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTING
14:37:51.657 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Waiting until process started: command 'git'.
14:37:51.661 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTED
14:37:51.662 [DEBUG] [org.gradle.process.internal.ExecHandleRunner] waiting until streams are handled...
14:37:51.663 [INFO] [org.gradle.process.internal.DefaultExecHandle] Successfully started process 'command 'git''
14:37:51.695 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: SUCCEEDED
14:37:51.696 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'command 'git'' finished with exit value 0 (state: SUCCEEDED)
14:37:51.697 [DEBUG] [ch.netzwerg.gradle.release.ReleaseTask] [detached HEAD 593f269] Prepare next release v0.0.6-SNAPSHOT
```

when adding the push entry in my build.gradle it is working.  
```
release{
   push=true
}
```

is the parameter ` -Prelease.push=true` incorrect?

**Comment by netzwerg** [comment]
Thanks for your feedback.

You are correct, there is a difference between project properties (-P) and extension properties (see e.g. http://gradle.1045684.n5.nabble.com/Extension-property-from-command-line-td5548804.html for details).

The `release` block is an extension. Thus, you have to configure it in your `build.gradle`.

One further issue I ran into myself: From the log it seems that you are building from `[detached HEAD 593f269]`.

> when adding the push entry in my build.gradle it is working.

This is quite surprising, because the plugin heavily relies on the assumption that you are releasing from `master`.

This is how you can configure Jenkins to build from `master`:

![screen shot 2015-01-27 at 15 18 26](https://cloud.githubusercontent.com/assets/439387/5920003/69883950-a639-11e4-9ab6-8e0c1e8adb41.png)
Hope this helps!

**Comment by Vad1mo** [comment]
By working I mean "push is triggered" :) 
Working with detached HEAD can be sometimes difficult especially in this case. so setting the branch name is the only option.
