### ISSUE TITLE
Provide different release tasks for upgrading different parts of the version

### ISSUE THREAD

**Issue by etiennestuder** [netzwerg/gradle-release-plugin#21]
Allow to bump up major, minor, or patch version through different Gradle tasks.

**Comment by netzwerg** [comment]
I have just published v1.1.0 which supports  `releaseMajorVersion` and `releaseMinorVersion` tasks. They bump the respective version parts *before* creating the release.

I didn't add a `releasePatchVersion` task though. IMHO it would have been confusing, since all release tasks bump the patch portion in preparation for the next dev cycle *after* creating the release.

Hope the new functionality still suits your needs...
