### ISSUE TITLE
pass in authentication credential and patch release

### ISSUE THREAD

**Issue by kknd22** [netzwerg/gradle-release-plugin#29]
This seems to be a fairly simple but very useful plugin. I got a questions:  
1. how to configure authentication username/password for git
2. Is there releasePatch task?

Thanks
-cl

**Comment by kknd22** [comment]
ok, release is the releasePatch that I asked for.

beside using ~/.netrc to passing in git credential, any better way?

**Comment by netzwerg** [comment]
Yes, `release` creates a patch version release. I created an issue to improve consistency with regards to these tasks (#30).

Concerning git credentials: Because the plugin just invokes the command-line git client, you are free to use your favourite [git credentials](https://git-scm.com/docs/gitcredentials) mechanism.

Just as an example: I personally use the [osxkeychain helper](https://help.github.com/articles/caching-your-github-password-in-git/) on my dev machine, and the Jenkins Credentials plugin on our CI server.
